# Generated by Django 5.0.6 on 2026-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applying_for_track',
            field=models.CharField(blank=True, choices=[('SCIENCE', 'Science'), ('ARTS', 'Arts'), ('COMMERCE', 'Commerce')], help_text='Only required for Grade 10-12 applicants (Senior Secondary): Science, Arts or Commerce.', max_length=10),
        ),
    ]
