# Generated by Django 5.0.6 on 2026-07-22 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_teacher_comment', models.TextField(blank=True)),
                ('principal_comment', models.TextField(blank=True)),
                ('average_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('class_position', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_total_days', models.PositiveIntegerField(blank=True, null=True)),
                ('attendance_present_days', models.PositiveIntegerField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=False, help_text='Must be ticked before the student can download it.')),
                ('generated_on', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='students.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='academics.term')),
            ],
            options={
                'unique_together': {('student', 'term')},
            },
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca_score', models.DecimalField(decimal_places=2, default=0, help_text='Continuous Assessment, out of 40', max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=0, help_text='Examination score, out of 60', max_digits=5)),
                ('teacher_remark', models.CharField(blank=True, max_length=255)),
                ('entered_on', models.DateTimeField(auto_now_add=True)),
                ('is_moderated', models.BooleanField(default=False, help_text='Ticked once a senior teacher/HoD has moderated this score.')),
                ('entered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.schoolclass')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='students.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='academics.term')),
            ],
            options={
                'ordering': ['student', 'subject'],
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
    ]
