# Generated by Django 5.0.6 on 2026-08-01 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('SENIOR_TEACHER', 'Senior Teacher'), ('TEACHER', 'Teacher'), ('BURSAR', 'Bursar'), ('SECRETARY', 'Office Secretary'), ('IT_SUPPORT', 'I.T Teacher / Support'), ('LIBRARIAN', 'Librarian'), ('NON_TEACHING', 'Non-Teaching Staff (Cleaner/Caretaker/Watchman)'), ('PARENT', 'Parent / Guardian'), ('STUDENT', 'Student'), ('APPLICANT', 'Applicant (pre-admission)'), ('CLUSTER_MONITOR', 'Cluster Monitor (MoBSE)')], max_length=30),
        ),
    ]
