# Generated by Django 5.0.6 on 2026-07-22 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='head_of_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_headed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='academics.department'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='subjects',
            field=models.ManyToManyField(blank=True, related_name='classes', to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='teacherassignment',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teaching_assignments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='term',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='academics.academicsession'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_slots', to='academics.schoolclass'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.subject'),
        ),
        migrations.AddField(
            model_name='timetableslot',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('grade', 'stream')},
        ),
        migrations.AlterUniqueTogether(
            name='teacherassignment',
            unique_together={('teacher', 'subject', 'school_class')},
        ),
        migrations.AlterUniqueTogether(
            name='term',
            unique_together={('session', 'name')},
        ),
    ]
