# Generated by Django 5.0.6 on 2026-07-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolclass',
            options={'ordering': ['grade', 'track', 'stream']},
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='capacity',
            field=models.PositiveIntegerField(default=45, help_text='Max students before auto-arrangement moves to the next stream.'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='track',
            field=models.CharField(choices=[('NONE', 'N/A (Upper Basic)'), ('SCIENCE', 'Science'), ('ARTS', 'Arts'), ('COMMERCE', 'Commerce')], default='NONE', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_core',
            field=models.BooleanField(default=True, help_text='Core (compulsory) subject vs elective.'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='period',
            field=models.PositiveSmallIntegerField(help_text='Period number, e.g. 1-8'),
        ),
        migrations.AlterUniqueTogether(
            name='schoolclass',
            unique_together={('grade', 'stream', 'track')},
        ),
    ]
